# Example configuration file for CLI usage.
# Intended for advanced users.

target: txt2img  # img2img not implemented.
# prompt can either be string or list.
# If prompt is list then the prompts are iterated in order.
prompt:
  - E=mc2  # prompt 1
  - hodl  # prompt 2
ddim_steps: 50  # legacy name, applies to all algorithms.
# Adding an int to toggles enables the corresponding feature.
# 0: Create prompt matrix (separate multiple prompts using |, and get all combinations of them)
# 1: Normalize Prompt Weights (ensure sum of weights add up to 1.0)
# 2: Save individual images
# 3: Save grid
# 4: Sort samples by prompt
# 5: Write sample info files
# 6: Fix faces using GFPGAN
# 7: Upscale images using Real-ESRGAN (NOT TESTED)
toggles: [1, 2, 3, 4, 5]
sampler_name: k_lms  # Valid: DDIM, k_dpm_2_a, k_dpm_2, k_euler_a, k_euler, k_heun, k_lms
ddim_eta: 0.0
n_iter: 1
batch_size: 1
cfg_scale: 7.5
seed: 3172010360 # Leave blank for random seed.
height: 512
width: 512
# The options below this line have not been tested. Use at your own discretion.
# Textual inversion embeddings file path:
fp:
realesrgan_model_name: